{
  "ActiveSkillStoneLevelConf": [
    {
      "ActiveSkillStoneLevelId": "101",
      "ActiveSkillStoneId": "1",
      "SkillLevel": "1",
      "SkillDemandLevel": "1",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "0",
      "SkillDemandIntelligence": "14",
      "ManaCost": "15",
      "CooldownMs": "500",
      "CastTimeMs": "0",
      "SkillRange": "15",
      "SkillRadius": "2",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "1",
      "DurationMs": "0",
      "SkillBaseMinValue": "18",
      "SkillBaseMaxValue": "27",
      "DamageType": "1"
    },
    {
      "ActiveSkillStoneLevelId": "102",
      "ActiveSkillStoneId": "1",
      "SkillLevel": "2",
      "SkillDemandLevel": "4",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "0",
      "SkillDemandIntelligence": "22",
      "ManaCost": "16",
      "CooldownMs": "500",
      "CastTimeMs": "0",
      "SkillRange": "16",
      "SkillRadius": "2",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "1",
      "DurationMs": "0",
      "SkillBaseMinValue": "24",
      "SkillBaseMaxValue": "36",
      "DamageType": "1"
    },
    {
      "ActiveSkillStoneLevelId": "201",
      "ActiveSkillStoneId": "2",
      "SkillLevel": "1",
      "SkillDemandLevel": "1",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "0",
      "SkillDemandIntelligence": "12",
      "ManaCost": "25",
      "CooldownMs": "4000",
      "CastTimeMs": "300",
      "SkillRange": "0",
      "SkillRadius": "4",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "0",
      "DurationMs": "0",
      "SkillBaseMinValue": "26",
      "SkillBaseMaxValue": "39",
      "DamageType": "2"
    },
    {
      "ActiveSkillStoneLevelId": "202",
      "ActiveSkillStoneId": "2",
      "SkillLevel": "2",
      "SkillDemandLevel": "5",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "0",
      "SkillDemandIntelligence": "20",
      "ManaCost": "26",
      "CooldownMs": "3800",
      "CastTimeMs": "280",
      "SkillRange": "0",
      "SkillRadius": "5",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "0",
      "DurationMs": "0",
      "SkillBaseMinValue": "34",
      "SkillBaseMaxValue": "51",
      "DamageType": "2"
    },
    {
      "ActiveSkillStoneLevelId": "301",
      "ActiveSkillStoneId": "3",
      "SkillLevel": "1",
      "SkillDemandLevel": "10",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "0",
      "SkillDemandIntelligence": "10",
      "ManaCost": "20",
      "CooldownMs": "3000",
      "CastTimeMs": "0",
      "SkillRange": "8",
      "SkillRadius": "0",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "0",
      "DurationMs": "0",
      "SkillBaseMinValue": "0",
      "SkillBaseMaxValue": "0",
      "DamageType": "5"
    },
    {
      "ActiveSkillStoneLevelId": "302",
      "ActiveSkillStoneId": "3",
      "SkillLevel": "2",
      "SkillDemandLevel": "16",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "0",
      "SkillDemandIntelligence": "18",
      "ManaCost": "20",
      "CooldownMs": "2800",
      "CastTimeMs": "0",
      "SkillRange": "9",
      "SkillRadius": "0",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "0",
      "DurationMs": "0",
      "SkillBaseMinValue": "0",
      "SkillBaseMaxValue": "0",
      "DamageType": "5"
    },
    {
      "ActiveSkillStoneLevelId": "401",
      "ActiveSkillStoneId": "4",
      "SkillLevel": "1",
      "SkillDemandLevel": "1",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "8",
      "SkillDemandIntelligence": "0",
      "ManaCost": "6",
      "CooldownMs": "0",
      "CastTimeMs": "0",
      "SkillRange": "2",
      "SkillRadius": "0",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "0",
      "DurationMs": "0",
      "SkillBaseMinValue": "12",
      "SkillBaseMaxValue": "18",
      "DamageType": "0"
    },
    {
      "ActiveSkillStoneLevelId": "402",
      "ActiveSkillStoneId": "4",
      "SkillLevel": "2",
      "SkillDemandLevel": "4",
      "SkillDemandWisdom": "0",
      "SkillDemandStrength": "16",
      "SkillDemandIntelligence": "0",
      "ManaCost": "7",
      "CooldownMs": "0",
      "CastTimeMs": "0",
      "SkillRange": "2",
      "SkillRadius": "0",
      "SkillWidth": "0",
      "SkillLength": "0",
      "ProjectileCount": "0",
      "DurationMs": "0",
      "SkillBaseMinValue": "18",
      "SkillBaseMaxValue": "27",
      "DamageType": "0"
    }
  ]
}
